services:
  postgres:
    image: postgres:17
    container_name: coffee-postgres

    environment:
      POSTGRES_USER: coffee_user
      POSTGRES_PASSWORD: coffee_password
      POSTGRES_DB: coffee_house

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres_data: