"""allow multiple payment attempts

Revision ID: 48a949f2c3ce
Revises: 720bc403f96d
Create Date: 2026-08-11 14:45:53.693382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48a949f2c3ce'
down_revision: Union[str, Sequence[str], None] = '720bc403f96d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_payments_order_id'), 'payments', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_payments_order_id'), 'payments', ['order_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
