"""add inventory to products

Revision ID: e661c3218a95
Revises: 91bea76ea8b3
Create Date: 2026-08-04 14:20:08.942052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e661c3218a95'
down_revision: Union[str, Sequence[str], None] = '91bea76ea8b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "products",
        sa.Column(
            "inventory",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    op.alter_column(
        "products",
        "inventory",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'inventory')
    # ### end Alembic commands ###
